disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Daniel Halawi"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "&copy; 2026 Daniel Halawi. All Rights Reserved."

[params.author]
   name = "Daniel Halawi"
   email = "HalawiDD@gmail.com"
   image = "mealteredbackground.webp"
   imageQuality = 96
#   headline = "Come Explore"
#   bio = "A little bit about you"
   links = [
     { email = "mailto:HalawiDD@gmail.com" },
     { github = "https://github.com/DannyShayH" }
   ]